spring:
    application:
        name: admin-server
    cloud:
        consul:
            config:
                fail-fast: ${FAIL_FAST:true}
                format: yaml
        kubernetes:
            discovery:
                service-labels:
                    spring-boot: true
    main:
        allow-bean-definition-overriding: true
    config:
        import: consul:${consul_url:localhost:8500}

