apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  annotations:
    cloud.google.com/app-protocols: '{"https-port":"HTTPS","http-port":"HTTP"}'
  labels:
    app: authentication-service
spec:
  ports:
    - name: https-port
      port: 8443
    - name: http-port
      port: 9999
  selector:
    app: authentication-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
spec:
  selector:
    matchLabels:
      app: authentication-service
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication-service
        version: v1
    spec:
      containers:
        - name: authentication-service
          image: fielcapao/microservices-design-patterns-authentication-service:latest #eu.gcr.io/api-project-646370370811/authentication-service #eu.gcr.io/api-project-646370370811/authentication-service:7f79c29fbc58052bb7d86bceeb7722b0185c66c4
          #          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"
          env:
            - name: JAVA_OPTS
              value: -Xms256m -Xmx512m
            - name: SERVER_PORT
              value: "9999"
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongodb:27017
            - name: SPRING_DATA_MONGODB_DATABASE
              value: docker
            - name: SPRING_REDIS_HOST
              value: redis
            - name: SPRING_CLOUD_CONSUL_ENABLED
              value: "false"
            - name: OPENTRACING_JAEGER_ENABLED
              value: "false"
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAMESPACE
              value: "default"
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: debug
            - name: CLIENT_ID
              value: ${CLIENT_ID}
            - name: CLIENT_SECRET
              value: ${CLIENT_SECRET}
          ports:
            - containerPort: 9999
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /actuator/health
              port: 9999
            initialDelaySeconds: 1000
            periodSeconds: 5
